!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Контекстная диаграмма системы «Тёплый дом»

Person(User, "Пользователь", "Управляет отоплением и просматривает данные о температуре")
Person(Technician, "Специалист", "Подключает устройства и настраивает систему")
System_Boundary(Monolith, "Монолитное приложение") {
    System(HeatingHouseSystem, "Heating house system", "Обработка запросов пользователя и управление устройствами")
}
System_Ext(Sensors, "Датчики температуры", "Передача данных о температуре")
System_Ext(HeatingDevices, "Устройства отопления", "Управление состоянием реле")
Rel(User, HeatingHouseSystem, "Управление отоплением и просмотр температуры")
Rel(Technician, HeatingHouseSystem, "Активация устройства")
Rel(Technician, Sensors, "Подключение датчика")
Rel(Technician, HeatingDevices, "Подключение устройства")
Rel(HeatingHouseSystem, HeatingDevices, "Команды управления реле")
Rel(HeatingHouseSystem, Sensors, "Запрос температуры")


